import React,{useState,useEffect}from'react';
import {View,Text,TouchableOpacity,StyleSheet,ScrollView,Alert,Modal,SafeAreaView}from'react-native';
import {signOut}from'firebase/auth';
import {doc,getDoc,collection,getDocs,query,where}from'firebase/firestore';
import {auth,db}from'../firebaseConfig';
export default function AnaSayfa({navigation}){const[kullaniciBilgi,setKullaniciBilgi]=useState(null),[siniflar,setSiniflar]=useState([]),[sinifModal,setSinifModal]=useState(false),[hedef,setHedef]=useState(null);
useEffect(()=>{(async()=>{try{const r=await getDoc(doc(db,'kullanicilar',auth.currentUser.uid));if(r.exists())setKullaniciBilgi(r.data())}catch(e){}try{const s=await getDocs(query(collection(db,'siniflar'),where('uid','==',auth.currentUser.uid)));setSiniflar(s.docs.map(d=>({id:d.id,...d.data()})))}catch(e){}})()},[]);
const cikis=()=>Alert.alert('Çıkış','Çıkış yapmak istediğinize emin misiniz?',[{text:'İptal',style:'cancel'},{text:'Çıkış Yap',style:'destructive',onPress:async()=>{try{await signOut(auth);navigation.replace('Giris')}catch(e){Alert.alert('Hata','Çıkış yapılamadı.')}}}]);
const sinifSec=s=>{setSinifModal(false);navigation.navigate(hedef,{sinif:s})};const ac=e=>{if(['Ogrenci','Kitap'].includes(e)){setHedef(e);setSinifModal(true)}else navigation.navigate(e)};
const donem=kullaniciBilgi?.sezon||kullaniciBilgi?.donem||kullaniciBilgi?.egitimOgretimDonemi||'2026–2027 Eğitim Öğretim Dönemi';const menuler=[['🏫','Okul & Sınıf','Okul ve sınıf yönetimi','OkulSinif'],['👨‍🎓','Öğrenciler','Sınıf seçerek öğrenci yönetimi','Ogrenci'],['📚','Kitap & Konular','Kitap ve konu takibi','Kitap'],['📅','Ders Takvimi','Haftalık ders programı','Takvim'],['✅','Yoklama','Öğrenci yoklama alma','Yoklama'],['📝','Ders Notları','İşlenen konular ve notlar','DersNotu'],['📋','Ödevler','Ödev takip ve hatırlatma','Odev'],['📊','Raporlar','Sınıf ve öğrenci raporları','Rapor']];
return <SafeAreaView style={styles.kapsayici}><ScrollView contentContainerStyle={{paddingBottom:30}}><View style={styles.ust}><View style={styles.kart}><View style={styles.kartUst}><View style={{flex:1}}><Text style={styles.hos}>Hoş Geldiniz 👋</Text><Text style={styles.isim}>{kullaniciBilgi?.kullaniciAdi||auth.currentUser?.displayName||'Öğretmen'}</Text><Text style={styles.brans}>{kullaniciBilgi?.brans||'Coğrafya'}</Text></View><View style={styles.donem}><Text style={styles.donemBas}>EĞİTİM ÖĞRETİM</Text><Text style={styles.donemMetin}>{donem}</Text></View></View></View></View><View style={styles.grid}>{menuler.map(([i,b,a,e])=><TouchableOpacity key={e} style={styles.menu} onPress={()=>ac(e)}><Text style={styles.icon}>{i}</Text><Text style={styles.bas}>{b}</Text><Text style={styles.alt}>{a}</Text></TouchableOpacity>)}</View><TouchableOpacity style={styles.cikis} onPress={cikis}><Text style={styles.cikisText}>🚪 Çıkış Yap</Text></TouchableOpacity></ScrollView><Modal visible={sinifModal} transparent animationType="slide"><View style={styles.modalBg}><View style={styles.modal}><Text style={styles.modalTitle}>Sınıf Seçin</Text><Text style={styles.modalSub}>{hedef==='Ogrenci'?'Öğrenciler':'Kitap & Konular'} için işlem yapılacak sınıfı seçin.</Text><ScrollView style={{maxHeight:420}}>{siniflar.map(s=><TouchableOpacity key={s.id} style={styles.sinifRow} onPress={()=>sinifSec(s)}><View><Text style={styles.sinifAd}>{s.ad}</Text><Text style={styles.okul}>{s.okulAd||'Okul belirtilmemiş'}</Text></View><Text style={styles.arrow}>›</Text></TouchableOpacity>)}{!siniflar.length&&<Text style={styles.empty}>Henüz sınıf tanımlanmamış.</Text>}</ScrollView><TouchableOpacity style={styles.cancel} onPress={()=>setSinifModal(false)}><Text>Kapat</Text></TouchableOpacity></View></View></Modal></SafeAreaView>}
const styles=StyleSheet.create({kapsayici:{flex:1,backgroundColor:'#F1F8E9'},ust:{padding:14,paddingTop:10},kart:{backgroundColor:'#2E7D32',borderRadius:16,padding:16,elevation:4},kartUst:{flexDirection:'row',alignItems:'center'},hos:{color:'#C8E6C9',fontSize:13},isim:{color:'#fff',fontSize:21,fontWeight:'bold',marginTop:3},brans:{color:'#A5D6A7',fontSize:13,marginTop:3},donem:{maxWidth:155,marginLeft:10,backgroundColor:'rgba(255,255,255,.13)',borderRadius:10,padding:9},donemBas:{color:'#C8E6C9',fontSize:9,fontWeight:'bold'},donemMetin:{color:'#fff',fontSize:12,fontWeight:'bold',marginTop:3},grid:{flexDirection:'row',flexWrap:'wrap',paddingHorizontal:10,gap:10},menu:{backgroundColor:'#fff',borderRadius:14,padding:15,width:'47%',elevation:2},icon:{fontSize:28,marginBottom:7},bas:{fontSize:14,fontWeight:'bold',color:'#1B5E20',marginBottom:4},alt:{fontSize:11,color:'#888'},cikis:{margin:18,padding:14,backgroundColor:'#fff',borderRadius:12,alignItems:'center',borderWidth:1,borderColor:'#FFCDD2'},cikisText:{color:'#C62828',fontWeight:'600',fontSize:15},modalBg:{flex:1,backgroundColor:'rgba(0,0,0,.5)',justifyContent:'flex-end'},modal:{backgroundColor:'#fff',borderTopLeftRadius:20,borderTopRightRadius:20,padding:20,maxHeight:'75%'},modalTitle:{fontSize:20,fontWeight:'bold',color:'#1B5E20'},modalSub:{fontSize:13,color:'#777',marginVertical:8},sinifRow:{padding:14,borderBottomWidth:1,borderBottomColor:'#eee',flexDirection:'row',justifyContent:'space-between',alignItems:'center'},sinifAd:{fontSize:16,fontWeight:'bold',color:'#333'},okul:{fontSize:12,color:'#777',marginTop:3},arrow:{fontSize:28,color:'#aaa'},empty:{padding:20,textAlign:'center',color:'#999'},cancel:{padding:14,alignItems:'center'}});