import React,{useState,useEffect} from 'react';
import {View,Text,TextInput,TouchableOpacity,StyleSheet,ScrollView,Alert,Modal,KeyboardAvoidingView,Platform} from 'react-native';
import {collection,addDoc,getDocs,query,where} from 'firebase/firestore';
import {auth,db} from '../firebaseConfig';
import {bugun,displayDate,oturumIdOlustur} from '../utils/oturum';
export default function DersNotuEkrani({route}){const ders=route?.params?.ders||null,tarih=route?.params?.oturumTarihi||bugun(),oturumId=route?.params?.oturumId||(ders?oturumIdOlustur(ders.id,tarih):null);const [siniflar,setSiniflar]=useState([]),[secili,setSecili]=useState(ders?{id:ders.sinifId,ad:ders.sinifAd,okulAd:ders.okulAd}:null),[notlar,setNotlar]=useState([]),[modal,setModal]=useState(!!ders),[yeni,setYeni]=useState(''),[loading,setLoading]=useState(false);const uid=auth.currentUser?.uid;
 useEffect(()=>{getDocs(query(collection(db,'siniflar'),where('uid','==',uid))).then(x=>setSiniflar(x.docs.map(d=>({id:d.id,...d.data()}))))},[]);const yukle=async s=>{setSecili(s);setLoading(true);try{const x=await getDocs(query(collection(db,'dersNotlari'),where('sinifId','==',s.id),where('uid','==',uid)));setNotlar(x.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.olusturulma||'').localeCompare(a.olusturulma||'')))}catch(e){Alert.alert('Hata','Ders notları yüklenemedi.')}setLoading(false)};useEffect(()=>{if(secili)yukle(secili)},[]);
 const ekle=async()=>{if(!yeni.trim()||!secili)return;try{await addDoc(collection(db,'dersNotlari'),{not:yeni.trim(),sinifId:secili.id,sinifAd:secili.ad,okulId:secili.okulId||ders?.okulId||'',okulAd:secili.okulAd||ders?.okulAd||'',tarih,oturumId:oturumId||null,dersId:ders?.id||null,gun:ders?.gun||'',baslangicSaat:ders?.baslangicSaat||'',bitisSaat:ders?.bitisSaat||'',uid,olusturulma:new Date().toISOString(),tarihGosterim:displayDate(tarih)});setYeni('');setModal(false);yukle(secili)}catch(e){Alert.alert('Hata','Konu kaydedilemedi.')}};
 return <View style={s.wrap}>{!ders&&<><Text style={s.label}>Sınıf Seçin</Text><ScrollView horizontal>{siniflar.map(x=><TouchableOpacity key={x.id} style={[s.chip,secili?.id===x.id&&s.active]} onPress={()=>yukle(x)}><Text style={secili?.id===x.id?s.activeT:{}}>{x.ad}</Text></TouchableOpacity>)}</ScrollView></>}{secili&&<TouchableOpacity style={s.add} onPress={()=>setModal(true)}><Text style={s.addT}>📝 Konu / Ders Notu Ekle</Text></TouchableOpacity>}<ScrollView contentContainerStyle={{padding:12,paddingBottom:90}}>{notlar.map(n=><View key={n.id} style={s.card}><Text style={s.date}>{n.tarihGosterim||displayDate(n.tarih)}</Text>{n.dersId?<Text style={s.session}>{n.baslangicSaat}–{n.bitisSaat} • {n.sinifAd}</Text>:null}<Text style={s.note}>{n.not}</Text></View>)}</ScrollView><Modal visible={modal} transparent animationType="slide"><KeyboardAvoidingView style={s.bg} behavior={Platform.OS==='ios'?'padding':'height'}><View style={s.modal}><ScrollView keyboardShouldPersistTaps="handled"><Text style={s.title}>Konu / Ders Notu</Text><Text style={s.sub}>{ders?`${ders.baslangicSaat}–${ders.bitisSaat} • ${ders.sinifAd}`:secili?.ad}</Text><TextInput style={s.input} value={yeni} onChangeText={setYeni} multiline autoFocus placeholder="Bugün hangi konuyu işlediniz?"/><TouchableOpacity style={s.save} onPress={ekle}><Text style={s.saveT}>Kaydet</Text></TouchableOpacity><TouchableOpacity onPress={()=>setModal(false)} style={s.cancel}><Text>İptal</Text></TouchableOpacity></ScrollView></View></KeyboardAvoidingView></Modal></View>}
const s=StyleSheet.create({wrap:{flex:1,backgroundColor:'#F1F8E9'},label:{padding:12,fontWeight:'bold',color:'#2E7D32'},chip:{borderWidth:1,borderColor:'#C8E6C9',backgroundColor:'#fff',borderRadius:20,padding:9,marginLeft:10},active:{backgroundColor:'#2E7D32'},activeT:{color:'#fff',fontWeight:'bold'},add:{margin:12,backgroundColor:'#2E7D32',padding:14,borderRadius:10,alignItems:'center'},addT:{color:'#fff',fontWeight:'bold'},card:{backgroundColor:'#fff',borderRadius:10,padding:13,marginBottom:8},date:{fontSize:11,color:'#888'},session:{fontSize:11,color:'#2E7D32',fontWeight:'bold',marginVertical:3},note:{fontSize:15,color:'#333'},bg:{flex:1,backgroundColor:'rgba(0,0,0,.5)',justifyContent:'flex-end'},modal:{backgroundColor:'#fff',borderTopLeftRadius:18,borderTopRightRadius:18,padding:20,maxHeight:'75%'},title:{fontSize:19,fontWeight:'bold',color:'#1B5E20'},sub:{color:'#777',marginVertical:8},input:{borderWidth:1,borderColor:'#C8E6C9',borderRadius:10,padding:13,minHeight:130,textAlignVertical:'top',fontSize:16},save:{backgroundColor:'#2E7D32',padding:15,borderRadius:10,alignItems:'center',marginTop:12},saveT:{color:'#fff',fontWeight:'bold'},cancel:{padding:14,alignItems:'center'}});
