import React,{useState,useEffect,useMemo}from'react';
import {View,Text,TextInput,TouchableOpacity,StyleSheet,ScrollView,Alert,Modal,KeyboardAvoidingView,Platform,SafeAreaView}from'react-native';
import {collection,addDoc,getDocs,query,where}from'firebase/firestore';
import {auth,db}from'../firebaseConfig';
import {bugun,displayDate,oturumIdOlustur}from'../utils/oturum';
import kazanmlar from'../assets/kazanimlar.json';
const normalize=t=>(t||'').toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const sinifKodlari=s=>{const k=String(s?.kademe||'');if(k==='TYT'||k==='AYT')return ['21','22'];if(k)return [k];const m=String(s?.ad||'').match(/(^|\D)([1-9]|1[0-2])(?:\D|$)/);return m?[m[2]]:[]};
export default function DersNotuEkrani({route}){
 const ders=route?.params?.ders||null,tarih=route?.params?.oturumTarihi||bugun(),oturumId=route?.params?.oturumId||(ders?oturumIdOlustur(ders.id,tarih):null);
 const [siniflar,setSiniflar]=useState([]),[secili,setSecili]=useState(ders?{id:ders.sinifId,ad:ders.sinifAd,okulAd:ders.okulAd,okulId:ders.okulId,kademe:ders.kademe,ders:ders.ders}:null),[notlar,setNotlar]=useState([]),[modal,setModal]=useState(!!ders),[yeni,setYeni]=useState(''),[csvModu,setCsvModu]=useState(false),[arama,setArama]=useState(''),[seciliKazanim,setSeciliKazanim]=useState(null),[sinifBilgi,setSinifBilgi]=useState(null);
 const uid=auth.currentUser?.uid;
 useEffect(()=>{getDocs(query(collection(db,'siniflar'),where('uid','==',uid))).then(x=>setSiniflar(x.docs.map(d=>({id:d.id,...d.data()})))).catch(()=>{})},[uid]);
 const yukle=async s=>{setSecili(s);setSinifBilgi(s);try{const x=await getDocs(query(collection(db,'dersNotlari'),where('sinifId','==',s.id),where('uid','==',uid)));setNotlar(x.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>new Date(b.olusturulma||b.tarih)-new Date(a.olusturulma||a.tarih)))}catch(e){Alert.alert('Hata','Ders notları yüklenemedi.')}};
 useEffect(()=>{if(secili)yukle(secili)},[]);
 const sonKonu=notlar[0]||null;
 const uygunKazanimlar=useMemo(()=>{const dersAdi=normalize(sinifBilgi?.ders||ders?.ders||'');const kodlar=sinifKodlari(sinifBilgi||secili||{});const a=normalize(arama.trim());if(!dersAdi||!kodlar.length||!a)return[];return kazanmlar.filter(k=>normalize(k.ders)===dersAdi&&kodlar.includes(String(k.sinif))).filter(k=>normalize(`${k.kod} ${k.ad}`).includes(a)).slice(0,80)},[sinifBilgi,secili,ders,arama]);
 const konuEkle=async()=>{const secilen=csvModu?seciliKazanim?.ad?.trim():yeni.trim();if(!secilen||!secili)return Alert.alert('Eksik bilgi','Bir konu yazın veya CSV listesinden konu seçin.');try{await addDoc(collection(db,'dersNotlari'),{not:secilen,sinifId:secili.id,sinifAd:secili.ad,okulId:secili.okulId||ders?.okulId||'',okulAd:secili.okulAd||ders?.okulAd||'',kademe:secili.kademe||'',ders:secili.ders||'',tarih,oturumId:oturumId||null,dersId:ders?.id||null,gun:ders?.gun||'',baslangicSaat:ders?.baslangicSaat||'',bitisSaat:ders?.bitisSaat||'',kazanımKodu:csvModu?(seciliKazanim?.kod||''):'',kaynak:csvModu?'csv':'manuel',uid,olusturulma:new Date().toISOString(),tarihGosterim:displayDate(tarih)});setYeni('');setArama('');setSeciliKazanim(null);setCsvModu(false);setModal(false);yukle(secili)}catch(e){Alert.alert('Hata','Konu kaydedilemedi.')}};
 return <SafeAreaView style={s.wrap}>
 {!ders&&<><Text style={s.label}>Sınıf Seçin</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{siniflar.map(x=><TouchableOpacity key={x.id} style={[s.chip,secili?.id===x.id&&s.active]} onPress={()=>yukle(x)}><Text style={secili?.id===x.id?s.activeT:s.chipT}>{x.ad}</Text><Text style={secili?.id===x.id?s.activeSub:s.school}>{x.okulAd||'Okul belirtilmemiş'}</Text><Text style={secili?.id===x.id?s.activeSub:s.school}>{x.kademe?`${x.kademe}. Sınıf`:''}{x.ders?` • ${x.ders}`:''}</Text></TouchableOpacity>)}</ScrollView></>}
 {secili&&<View style={s.ozet}><Text style={s.ozetBas}>Son işlenen konu</Text><Text style={s.ozetKonu}>{sonKonu?.not||'Henüz konu girilmemiş.'}</Text>{sonKonu&&<Text style={s.ozetAlt}>{sonKonu.tarihGosterim||displayDate(sonKonu.tarih)}</Text>}<TouchableOpacity style={s.add} onPress={()=>setModal(true)}><Text style={s.addT}>+ Konu Ekle</Text></TouchableOpacity></View>}
 <ScrollView contentContainerStyle={{padding:12,paddingBottom:110}}>{notlar.length===0&&secili&&<Text style={s.bos}>Bu sınıf için henüz işlenen konu kaydı yok.</Text>}{notlar.map(n=><View key={n.id} style={s.card}><Text style={s.date}>{n.tarihGosterim||displayDate(n.tarih)}</Text>{n.dersId?<Text style={s.session}>{n.baslangicSaat}–{n.bitisSaat} • {n.sinifAd}</Text>:null}<Text style={s.note}>{n.kazanımKodu?`${n.kazanımKodu} — `:''}{n.not}</Text></View>)}</ScrollView>
 <Modal visible={modal} transparent animationType="slide"><KeyboardAvoidingView style={s.bg} behavior={Platform.OS==='ios'?'padding':'height'}><View style={s.modal}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{paddingBottom:30}}><Text style={s.title}>Konu Ekle</Text><Text style={s.sub}>{secili?`${secili.ad}${secili.ders?` • ${secili.ders}`:''}`:''}</Text><View style={s.secimSatir}><TouchableOpacity style={[s.secim,csvModu&&s.secimAktif]} onPress={()=>{setCsvModu(true);setYeni('')}}><Text style={[s.secimText,csvModu&&s.secimTextAktif]}>CSV'den seç</Text></TouchableOpacity><TouchableOpacity style={[s.secim,!csvModu&&s.secimAktif]} onPress={()=>{setCsvModu(false);setSeciliKazanim(null)}}><Text style={[s.secimText,!csvModu&&s.secimTextAktif]}>Kendim yazacağım</Text></TouchableOpacity></View>{csvModu?<><Text style={s.kucuk}>{secili?.kademe||'Kademe'} • {secili?.ders||'Ders'} — yalnızca bu sınıfa uygun CSV kayıtları</Text><TextInput style={s.input} value={arama} onChangeText={setArama} placeholder="Konu / kazanım ara..." />{arama.trim()&&uygunKazanimlar.map(k=><TouchableOpacity key={`${k.sinif}-${k.kod}-${k.ad}`} style={[s.kazanim,seciliKazanim?.kod===k.kod&&s.kazanimSecili]} onPress={()=>setSeciliKazanim(k)}><Text style={s.kod}>{k.kod}</Text><Text style={s.kazanimAd}>{k.ad}</Text></TouchableOpacity>)}{arama.trim()&&!uygunKazanimlar.length&&<Text style={s.bos}>Uygun CSV kaydı bulunamadı.</Text>}{seciliKazanim&&<Text style={s.secilen}>Seçilen: {seciliKazanim.kod} — {seciliKazanim.ad}</Text>}</>:<TextInput style={[s.input,{minHeight:120}]} value={yeni} onChangeText={setYeni} multiline autoFocus placeholder="Bugün hangi konuyu işlediniz?"/>}<TouchableOpacity style={s.save} onPress={konuEkle}><Text style={s.saveT}>Kaydet</Text></TouchableOpacity><TouchableOpacity onPress={()=>setModal(false)} style={s.cancel}><Text>İptal</Text></TouchableOpacity></ScrollView></View></KeyboardAvoidingView></Modal>
 </SafeAreaView>;
}
const s=StyleSheet.create({wrap:{flex:1,backgroundColor:'#F1F8E9'},label:{padding:12,fontWeight:'bold',color:'#2E7D32'},chips:{paddingBottom:4},chip:{borderWidth:1,borderColor:'#C8E6C9',backgroundColor:'#fff',borderRadius:12,padding:9,marginLeft:10,minWidth:120},chipT:{fontWeight:'600',color:'#333'},school:{fontSize:10,color:'#777',marginTop:3},active:{backgroundColor:'#2E7D32',borderColor:'#2E7D32'},activeT:{color:'#fff',fontWeight:'bold'},activeSub:{fontSize:10,color:'#C8E6C9',marginTop:3},ozet:{margin:12,backgroundColor:'#fff',borderRadius:12,padding:14,elevation:2},ozetBas:{fontSize:12,fontWeight:'bold',color:'#558B2F'},ozetKonu:{fontSize:16,fontWeight:'bold',color:'#1B5E20',marginTop:4},ozetAlt:{fontSize:11,color:'#888',marginTop:4},add:{marginTop:12,backgroundColor:'#2E7D32',padding:13,borderRadius:10,alignItems:'center'},addT:{color:'#fff',fontWeight:'bold'},card:{backgroundColor:'#fff',borderRadius:10,padding:13,marginBottom:8},date:{fontSize:11,color:'#888'},session:{fontSize:11,color:'#2E7D32',fontWeight:'bold',marginVertical:3},note:{fontSize:15,color:'#333'},bos:{color:'#999',textAlign:'center',padding:20},bg:{flex:1,backgroundColor:'rgba(0,0,0,.5)',justifyContent:'flex-end'},modal:{backgroundColor:'#fff',borderTopLeftRadius:18,borderTopRightRadius:18,padding:20,maxHeight:'86%'},title:{fontSize:19,fontWeight:'bold',color:'#1B5E20'},sub:{color:'#777',marginVertical:8},input:{borderWidth:1,borderColor:'#C8E6C9',borderRadius:10,padding:13,fontSize:16,marginBottom:10,backgroundColor:'#fff'},secimSatir:{flexDirection:'row',gap:8,marginBottom:10},secim:{flex:1,borderWidth:1,borderColor:'#C8E6C9',borderRadius:9,padding:11,alignItems:'center'},secimAktif:{backgroundColor:'#2E7D32',borderColor:'#2E7D32'},secimText:{fontSize:12,color:'#333'},secimTextAktif:{color:'#fff',fontWeight:'bold'},kucuk:{fontSize:11,color:'#558B2F',marginBottom:8},kazanim:{borderWidth:1,borderColor:'#E8F5E9',borderRadius:9,padding:10,marginBottom:7},kazanimSecili:{backgroundColor:'#E8F5E9',borderColor:'#2E7D32'},kod:{fontSize:11,color:'#2E7D32',fontWeight:'bold'},kazanimAd:{fontSize:13,color:'#333',marginTop:2},secilen:{backgroundColor:'#E8F5E9',padding:10,borderRadius:8,marginBottom:8},save:{backgroundColor:'#2E7D32',padding:15,borderRadius:10,alignItems:'center',marginTop:4},saveT:{color:'#fff',fontWeight:'bold'},cancel:{padding:14,alignItems:'center'}});