import React,{useState,useEffect} from 'react';
import {View,Text,TextInput,TouchableOpacity,StyleSheet,ScrollView,Alert,Modal,SafeAreaView,KeyboardAvoidingView,Platform} from 'react-native';
import {collection,addDoc,getDocs,updateDoc,doc,query,where} from 'firebase/firestore';
import {auth,db} from '../firebaseConfig';
import {bugun,displayDate,oturumIdOlustur} from '../utils/oturum';
const renk={yapildi:'#2E7D32',yapilmadi:'#C62828',gec:'#F57F17',bekliyor:'#1565C0'},ikon={yapildi:'✅',yapilmadi:'❌',gec:'⏰',bekliyor:'📋'};
function CalendarPicker({visible,value,onClose,onSelect}) {
  const [d,setD]=useState(value?new Date(value+'T12:00:00'):new Date());
  useEffect(()=>{ if(visible) setD(value?new Date(value+'T12:00:00'):new Date()); },[visible,value]);
  const y=d.getFullYear(), m=d.getMonth();
  const ilk=(new Date(y,m,1).getDay()+6)%7;
  const g=new Date(y,m+1,0).getDate();
  const ay=['Ocak','Şubat','Mart','Nisan','Mayıs','Haziran','Temmuz','Ağustos','Eylül','Ekim','Kasım','Aralık'];
  return (
    <Modal visible={visible} transparent>
      <View style={s.bg}>
        <View style={s.cal}>
          <View style={s.head}>
            <TouchableOpacity onPress={()=>setD(new Date(y,m-1,1))}><Text style={s.arrow}>‹</Text></TouchableOpacity>
            <Text style={s.calTitle}>{ay[m]} {y}</Text>
            <TouchableOpacity onPress={()=>setD(new Date(y,m+1,1))}><Text style={s.arrow}>›</Text></TouchableOpacity>
          </View>
          <View style={s.week}>{['Pzt','Sal','Çar','Per','Cum','Cmt','Paz'].map(x=><Text key={x} style={s.weekT}>{x}</Text>)}</View>
          <View style={s.grid}>
            {Array.from({length:ilk+g},(_,i)=>{
              if(i<ilk) return <View key={i} style={s.day}/>;
              const n=i-ilk+1;
              const dt=`${y}-${String(m+1).padStart(2,'0')}-${String(n).padStart(2,'0')}`;
              return <TouchableOpacity key={i} style={s.day} onPress={()=>{onSelect(dt);onClose()}}><Text style={[s.dayT,value===dt&&s.daySel]}>{n}</Text></TouchableOpacity>;
            })}
          </View>
          <TouchableOpacity onPress={onClose} style={s.cancel}><Text>Kapat</Text></TouchableOpacity>
        </View>
      </View>
    </Modal>
  );
}

export default function OdevEkrani({route}){const ders=route?.params?.ders||null,tarih=route?.params?.oturumTarihi||bugun(),oturumId=route?.params?.oturumId||(ders?oturumIdOlustur(ders.id,tarih):null);const [siniflar,setSiniflar]=useState([]),[secili,setSecili]=useState(ders?{id:ders.sinifId,ad:ders.sinifAd,okulAd:ders.okulAd}:null),[ogr,setOgr]=useState([]),[odev,setOdev]=useState([]),[modal,setModal]=useState(!!ders),[edit,setEdit]=useState(null),[aciklama,setAciklama]=useState(''),[teslim,setTeslim]=useState(''),[hedef,setHedef]=useState('sinif'),[ids,setIds]=useState([]),[cal,setCal]=useState(false),[durum,setDurum]=useState(null);
 const uid=auth.currentUser?.uid;useEffect(()=>{getDocs(query(collection(db,'siniflar'),where('uid','==',uid))).then(x=>setSiniflar(x.docs.map(d=>({id:d.id,...d.data()}))))},[]);const yukle=async x=>{setSecili(x);try{const [a,b]=await Promise.all([getDocs(query(collection(db,'odevler'),where('sinifId','==',x.id),where('uid','==',uid))),getDocs(query(collection(db,'ogrenciler'),where('sinifId','==',x.id),where('uid','==',uid)))]);setOdev(a.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.olusturulma||'').localeCompare(a.olusturulma||'')));setOgr(b.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.adSoyad||'').localeCompare(b.adSoyad||'')))}catch(e){Alert.alert('Hata','Ödevler yüklenemedi.')}};useEffect(()=>{if(secili)yukle(secili)},[]);
 const temiz=()=>{setAciklama('');setTeslim('');setHedef('sinif');setIds([]);setEdit(null);setModal(false)};const ac=()=>{temiz();setModal(true)};const toggle=id=>setIds(p=>p.includes(id)?p.filter(x=>x!==id):[...p,id]);
 const kaydet=async()=>{if(!secili||!aciklama.trim()||!teslim)return Alert.alert('Eksik bilgi','Ödev açıklaması ve teslim tarihi zorunludur.');const hedefler=hedef==='sinif'?ogr:ogr.filter(x=>ids.includes(x.id));if(!hedefler.length)return Alert.alert('Eksik bilgi','En az bir öğrenci seçin.');try{const now=new Date().toISOString();if(edit){await updateDoc(doc(db,'odevler',edit.id),{aciklama:aciklama.trim(),teslimTarihi:teslim,hedef,hedefOgrenciIds:hedefler.map(x=>x.id),hedefOgrenciAdlari:hedefler.map(x=>x.adSoyad)})}else{const durumlar={},gecmis={};hedefler.forEach(x=>{durumlar[x.id]='bekliyor';gecmis[x.id]=[{durum:'bekliyor',tarih:now,tarihGosterim:displayDate(tarih)}]});await addDoc(collection(db,'odevler'),{aciklama:aciklama.trim(),teslimTarihi:teslim,hedef,sinifId:secili.id,sinifAd:secili.ad,okulId:secili.okulId||ders?.okulId||'',okulAd:secili.okulAd||ders?.okulAd||'',hedefOgrenciIds:hedefler.map(x=>x.id),hedefOgrenciAdlari:hedefler.map(x=>x.adSoyad),ogrenciDurumlari:durumlar,durumGecmisi:gecmis,dersId:ders?.id||null,oturumId:oturumId||null,tarih,gun:ders?.gun||'',baslangicSaat:ders?.baslangicSaat||'',bitisSaat:ders?.bitisSaat||'',uid,olusturulma:now})}temiz();yukle(secili)}catch(e){Alert.alert('Hata','Ödev kaydedilemedi.')}};
 const durumGuncelle=async(o,id,d)=>{try{const durumlar={...(o.ogrenciDurumlari||{})},gecmis={...(o.durumGecmisi||{})};durumlar[id]=d;gecmis[id]=[...(gecmis[id]||[]),{durum:d,tarih:new Date().toISOString(),tarihGosterim:displayDate(isoDateNow())}];await updateDoc(doc(db,'odevler',o.id),{ogrenciDurumlari:durumlar,durumGecmisi:gecmis,durum:d});setDurum(null);yukle(secili)}catch(e){Alert.alert('Hata','Durum güncellenemedi.')}};
 const isoDateNow=()=>bugun();const duzenle=o=>{setEdit(o);setAciklama(o.aciklama||'');setTeslim(o.teslimTarihi||'');setHedef(o.hedef||'sinif');setIds(o.hedefOgrenciIds||[]);setModal(true)};
 return <SafeAreaView style={s.wrap}>{!ders&&<><Text style={s.label}>Sınıf Seçin</Text><ScrollView horizontal>{siniflar.map(x=><TouchableOpacity key={x.id} style={[s.chip,secili?.id===x.id&&s.active]} onPress={()=>yukle(x)}><Text style={secili?.id===x.id?s.activeT:{}}>{x.ad}</Text></TouchableOpacity>)}</ScrollView></>}{secili&&<TouchableOpacity style={s.add} onPress={ac}><Text style={s.addT}>📋 Ödev Ekle</Text></TouchableOpacity>}<ScrollView contentContainerStyle={{padding:12,paddingBottom:90}}>{odev.map(o=><View key={o.id} style={s.card}><TouchableOpacity onPress={()=>duzenle(o)}><Text style={s.title}>{o.aciklama}</Text><Text style={s.meta}>📅 Teslim: {displayDate(o.teslimTarihi)} · {o.hedef==='bireysel'?'👤 Bireysel':'👥 Tüm sınıf'}</Text></TouchableOpacity><View style={s.stats}>{(o.hedefOgrenciIds||[]).map(id=>{const x=ogr.find(z=>z.id===id);const d=o.ogrenciDurumlari?.[id]||'bekliyor';return <TouchableOpacity key={id} style={s.studentRow} onPress={()=>setDurum({o,id,name:x?.adSoyad||'Öğrenci'})}><Text style={{flex:1}}>{x?.adSoyad||'Öğrenci'}</Text><Text style={{color:renk[d],fontWeight:'bold'}}>{ikon[d]} {d==='yapildi'?'Yaptı':d==='yapilmadi'?'Yapmadı':d==='gec'?'Geç getirdi':'Bekliyor'}</Text></TouchableOpacity>})}</View></View>)}</ScrollView>
 <Modal visible={modal} transparent animationType="slide"><KeyboardAvoidingView style={s.bg} behavior={Platform.OS==='ios'?'padding':'height'}><View style={s.form}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{paddingBottom:30}}><Text style={s.formTitle}>{edit?'Ödevi Düzenle':'Ödev Ekle'}</Text><Text style={s.label}>Ödev</Text><TextInput style={s.input} value={aciklama} onChangeText={setAciklama} multiline placeholder="Ödev açıklaması"/><Text style={s.label}>Teslim Tarihi</Text><TouchableOpacity style={s.dateBtn} onPress={()=>setCal(true)}><Text>{teslim?displayDate(teslim):'📅 Tarih seçin'}</Text></TouchableOpacity><Text style={s.label}>Hedef</Text><View style={s.two}>{['sinif','bireysel'].map(x=><TouchableOpacity key={x} style={[s.choice,hedef===x&&s.active]} onPress={()=>setHedef(x)}><Text style={hedef===x?s.activeT:{}}>{x==='sinif'?'👥 Tüm Sınıf':'👤 Bireysel'}</Text></TouchableOpacity>)}</View>{hedef==='bireysel'&&<><Text style={s.label}>Öğrenciler ({ids.length})</Text><TouchableOpacity onPress={()=>setIds(ids.length===ogr.length?[]:ogr.map(x=>x.id))}><Text style={{color:'#1565C0',fontWeight:'bold',marginBottom:6}}>{ids.length===ogr.length?'Seçimleri kaldır':'Tümünü seç'}</Text></TouchableOpacity><View style={s.picker}>{ogr.map(x=><TouchableOpacity key={x.id} style={s.pick} onPress={()=>toggle(x.id)}><Text style={s.check}>{ids.includes(x.id)?'☑':'☐'}</Text><Text>{x.adSoyad}</Text></TouchableOpacity>)}</View></>}<TouchableOpacity style={s.save} onPress={kaydet}><Text style={s.saveT}>{edit?'Güncelle':'Kaydet'}</Text></TouchableOpacity><TouchableOpacity onPress={temiz} style={s.cancel}><Text>İptal</Text></TouchableOpacity></ScrollView></View></KeyboardAvoidingView></Modal><CalendarPicker visible={cal} value={teslim} onClose={()=>setCal(false)} onSelect={setTeslim}/><Modal visible={!!durum} transparent><View style={s.bg}><View style={s.status}><Text style={s.formTitle}>{durum?.name}</Text>{['yapildi','gec','yapilmadi'].map(d=><TouchableOpacity key={d} style={[s.statusBtn,{borderColor:renk[d]}]} onPress={()=>durumGuncelle(durum.o,durum.id,d)}><Text style={{color:renk[d],fontWeight:'bold'}}>{ikon[d]} {d==='yapildi'?'Yaptı':d==='gec'?'Geç getirdi':'Yapmadı'}</Text></TouchableOpacity>)}<TouchableOpacity style={s.cancel} onPress={()=>setDurum(null)}><Text>İptal</Text></TouchableOpacity></View></View></Modal></SafeAreaView>}
const s=StyleSheet.create({wrap:{flex:1,backgroundColor:'#F1F8E9'},label:{fontWeight:'bold',color:'#2E7D32',paddingHorizontal:12,paddingTop:10,paddingBottom:6},chip:{borderWidth:1,borderColor:'#C8E6C9',backgroundColor:'#fff',borderRadius:20,padding:9,marginLeft:10},active:{backgroundColor:'#2E7D32',borderColor:'#2E7D32'},activeT:{color:'#fff',fontWeight:'bold'},add:{margin:12,backgroundColor:'#2E7D32',padding:14,borderRadius:10,alignItems:'center'},addT:{color:'#fff',fontWeight:'bold'},card:{backgroundColor:'#fff',borderRadius:12,padding:14,marginBottom:10},title:{fontSize:16,fontWeight:'bold',color:'#1B5E20'},meta:{fontSize:12,color:'#666',marginTop:5},stats:{marginTop:8},studentRow:{flexDirection:'row',paddingVertical:9,borderBottomWidth:1,borderBottomColor:'#eee'},bg:{flex:1,backgroundColor:'rgba(0,0,0,.5)',justifyContent:'flex-end'},form:{backgroundColor:'#fff',borderTopLeftRadius:18,borderTopRightRadius:18,padding:20,maxHeight:'88%'},formTitle:{fontSize:19,fontWeight:'bold',color:'#1B5E20',marginBottom:8},input:{borderWidth:1,borderColor:'#C8E6C9',borderRadius:10,padding:12,minHeight:90,textAlignVertical:'top'},dateBtn:{borderWidth:1,borderColor:'#C8E6C9',borderRadius:10,padding:14},two:{flexDirection:'row',gap:8},choice:{flex:1,borderWidth:1,borderColor:'#C8E6C9',padding:12,borderRadius:9,alignItems:'center'},picker:{borderWidth:1,borderColor:'#ddd',borderRadius:10,maxHeight:240},pick:{flexDirection:'row',padding:11,borderBottomWidth:1,borderBottomColor:'#eee'},check:{fontSize:19,color:'#2E7D32',marginRight:8},save:{backgroundColor:'#2E7D32',padding:15,borderRadius:10,alignItems:'center',marginTop:16},saveT:{color:'#fff',fontWeight:'bold'},cancel:{padding:13,alignItems:'center'},cal:{backgroundColor:'#fff',borderRadius:18,padding:18},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},arrow:{fontSize:32,color:'#2E7D32'},calTitle:{fontSize:17,fontWeight:'bold',color:'#1B5E20'},week:{flexDirection:'row',marginVertical:8},weekT:{flex:1,textAlign:'center',fontSize:11,color:'#777'},grid:{flexDirection:'row',flexWrap:'wrap'},day:{width:'14.2857%',aspectRatio:1,alignItems:'center',justifyContent:'center'},dayT:{width:34,height:34,textAlign:'center',textAlignVertical:'center',borderRadius:17},daySel:{backgroundColor:'#2E7D32',color:'#fff',fontWeight:'bold'},status:{backgroundColor:'#fff',borderRadius:18,padding:20},statusBtn:{borderWidth:1,padding:13,borderRadius:10,marginVertical:4,alignItems:'center'}});
