import React,{useState,useEffect}from'react';
import {View,Text,TouchableOpacity,StyleSheet,ScrollView,ActivityIndicator,Modal,BackHandler}from'react-native';
import {collection,getDocs,query,where}from'firebase/firestore';
import {auth,db}from'../firebaseConfig';
const statusText=d=>d==='yapildi'?'✅ Yaptı':d==='yapilmadi'?'❌ Yapmadı':d==='gec'?'⏰ Geç getirdi':'📋 Bekliyor';
const sayfaAdedi=k=>Math.max(0,(parseInt(k?.bitisSayfa,10)||0)-(parseInt(k?.baslangicSayfa,10)||0)+1);
const zaman=v=>new Date(v||0).getTime()||0;
export default function RaporEkrani({navigation,route}){
 const[siniflar,setSiniflar]=useState([]),[seciliSinif,setSeciliSinif]=useState(route?.params?.sinif||null),[notlar,setNotlar]=useState([]),[yoklamalar,setYoklamalar]=useState([]),[odevler,setOdevler]=useState([]),[ogrenciler,setOgrenciler]=useState([]),[konular,setKonular]=useState([]),[kitaplar,setKitaplar]=useState([]),[yukleniyor,setYukleniyor]=useState(false),[sekme,setSekme]=useState('notlar'),[detay,setDetay]=useState(route?.params?.ogrenci||null);
 const uid=auth.currentUser?.uid;
 useEffect(()=>{getDocs(query(collection(db,'siniflar'),where('uid','==',uid))).then(x=>setSiniflar(x.docs.map(d=>({id:d.id,...d.data()})))).catch(()=>{})},[uid]);
 useEffect(()=>{const h=BackHandler.addEventListener('hardwareBackPress',()=>{if(detay){setDetay(null);return true}return false});return()=>h.remove()},[detay]);
 const sinifSec=async sinif=>{setSeciliSinif(sinif);setYukleniyor(true);try{const cols=['dersNotlari','yoklamalar','odevler','ogrenciler','konular','kitaplar'];const r=await Promise.all(cols.map(c=>getDocs(query(collection(db,c),where('sinifId','==',sinif.id),where('uid','==',uid)))));setNotlar(r[0].docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>zaman(b.olusturulma||b.tarih)-zaman(a.olusturulma||a.tarih)));setYoklamalar(r[1].docs.map(x=>({id:x.id,...x.data()})));setOdevler(r[2].docs.map(x=>({id:x.id,...x.data()})));setOgrenciler(r[3].docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>(a.adSoyad||'').localeCompare(b.adSoyad||'')));setKonular(r[4].docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>zaman(b.olusturulma||b.tarih)-zaman(a.olusturulma||a.tarih)));setKitaplar(r[5].docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>zaman(a.olusturulma)-zaman(b.olusturulma)));const hedef=route?.params?.ogrenci;if(hedef&&hedef.sinifId===sinif.id)setDetay(hedef)}catch(e){}setYukleniyor(false)};
 useEffect(()=>{if(seciliSinif)sinifSec(seciliSinif)},[]);
 const yoklamaOzeti=()=>{const o={};yoklamalar.forEach(y=>{const id=y.ogrenciId||y.ogrenciAd;if(!o[id])o[id]={geldi:0,gecikti:0,gelmedi:0};o[id][y.durum]=(o[id][y.durum]||0)+1});return o};
 const studentAttendance=id=>yoklamalar.filter(y=>y.ogrenciId===id).sort((a,b)=>String(b.tarih||'').localeCompare(String(a.tarih||'')));
 const studentHomework=id=>odevler.filter(o=>o.hedef==='sinif'||o.hedef==='tumSinif'||o.tumSinif===true||(o.hedefOgrenciIds||[]).includes(id)).sort((a,b)=>zaman(a.olusturulma||a.teslimTarihi)-zaman(b.olusturulma||b.teslimTarihi));
 const studentTopics=id=>{const kitapKonular=konular.filter(k=>k.ogrenciId===id).sort((a,b)=>zaman(b.olusturulma||b.tarih)-zaman(a.olusturulma||a.tarih));const dersKonular=notlar.map(n=>{let y=yoklamalar.find(v=>v.ogrenciId===id&&n.oturumId&&v.oturumId===n.oturumId);if(!y)y=yoklamalar.find(v=>v.ogrenciId===id&&n.dersId&&v.dersId===n.dersId&&String(v.tarih||'').slice(0,10)===String(n.tarih||'').slice(0,10));return{id:'not-'+n.id,ad:n.not||'İşlenen konu',kitapAd:n.kitapAd||'',tarih:n.tarih,tarihGosterim:n.tarihGosterim,olusturulma:n.olusturulma,dersteYok:y?.durum==='gelmedi',yoklamaDurumu:y?.durum||null}});return{kitap:kitapKonular,ders:dersKonular.sort((a,b)=>zaman(b.olusturulma||b.tarih)-zaman(a.olusturulma||a.tarih))};};
 const konuOdevDurumu=k=>{const h=odevler.filter(o=>o.konuId===k.id&&((o.hedef==='sinif'&&o.sinifId===seciliSinif?.id)||(o.hedefOgrenciIds||[]).includes(detay?.id)));if(!h.length)return null;const latest=[...h].sort((a,b)=>zaman(b.olusturulma)-zaman(a.olusturulma))[0];return latest.ogrenciDurumlari?.[detay?.id]||latest.durum||'bekliyor'};
 const kitapIlerleme=k=>{const ks=konular.filter(x=>x.kitapId===k.id),done=ks.reduce((sum,x)=>konuOdevDurumu(x)==='yapildi'?sum+sayfaAdedi(x):sum,0),total=parseInt(k.sayfaSayisi,10)||0;return{done:total?Math.min(done,total):done,total,pct:total?Math.min(100,Math.round(done/total*100)):0}};
 return <View style={s.wrap}><Text style={s.baslik}>Sınıf Seçin:</Text><ScrollView horizontal style={s.sinifListesi} showsHorizontalScrollIndicator={false}>{siniflar.map(x=><TouchableOpacity key={x.id} style={[s.sinifButon,seciliSinif?.id===x.id&&s.sinifAktif]} onPress={()=>sinifSec(x)}><Text style={[s.sinifMetni,seciliSinif?.id===x.id&&s.sinifMetniAktif]}>{x.ad}</Text><Text style={seciliSinif?.id===x.id?s.chipOkulAktif:s.chipOkul}>{x.okulAd||'Okul belirtilmemiş'}</Text><Text style={seciliSinif?.id===x.id?s.chipAltAktif:s.chipAlt}>{x.kademe?`${x.kademe}. Sınıf`:''}{x.ders?` • ${x.ders}`:''}</Text></TouchableOpacity>)}</ScrollView>{seciliSinif&&<View style={s.sekmeler}>{[['notlar','📖 Notlar'],['yoklama','✅ Yoklama'],['odevler','📋 Ödevler'],['ogrenciler','👤 Öğrenciler']].map(([k,t])=><TouchableOpacity key={k} style={[s.sekme,sekme===k&&s.sekmeAktif]} onPress={()=>setSekme(k)}><Text style={sekme===k?s.sekmeMetniAktif:s.sekmeMetni}>{t}</Text></TouchableOpacity>)}</View>}{yukleniyor?<ActivityIndicator style={{marginTop:32}} size="large" color="#2E7D32"/>:<ScrollView style={s.icerik} contentContainerStyle={{paddingBottom:110}}>{!seciliSinif?<Text style={s.bos}>Rapor görmek için sınıf seçin.</Text>:null}{seciliSinif&&sekme==='notlar'&&notlar.map(n=><View key={n.id} style={s.card}><Text style={s.small}>{n.tarihGosterim||n.tarih}</Text><Text style={s.cardText}>{n.not}</Text></View>)}{seciliSinif&&sekme==='yoklama'&&ogrenciler.map(o=>{const z=yoklamaOzeti()[o.id]||{};return <TouchableOpacity key={o.id} style={s.card} onPress={()=>setDetay(o)}><Text style={s.student}>{o.adSoyad}</Text><Text style={s.small}>Geldi {z.geldi||0} • Geçti {z.gecikti||0} • Gelmedi {z.gelmedi||0}</Text></TouchableOpacity>})}{seciliSinif&&sekme==='odevler'&&[...odevler].sort((a,b)=>zaman(b.olusturulma||b.teslimTarihi)-zaman(a.olusturulma||a.teslimTarihi)).map(o=><View key={o.id} style={s.card}><Text style={s.cardText}>{o.aciklama}</Text><Text style={s.small}>Teslim: {o.teslimTarihi}</Text></View>)}{seciliSinif&&sekme==='ogrenciler'&&ogrenciler.map(o=><TouchableOpacity key={o.id} style={s.card} onPress={()=>setDetay(o)}><Text style={s.student}>{o.adSoyad} ›</Text><Text style={s.small}>Yoklama · Konular · Kitap İlerlemesi · Ödevler</Text></TouchableOpacity>)}</ScrollView>}
 <Modal visible={!!detay} animationType="slide" onRequestClose={()=>setDetay(null)}><View style={s.detail}><View style={s.detailHead}><View style={{flex:1}}><Text style={s.detailTitle}>{detay?.adSoyad}</Text><Text style={s.small}>{seciliSinif?.okulAd||''} {seciliSinif?.kademe?`• ${seciliSinif.kademe}. Sınıf`:''} {seciliSinif?.ders?`• ${seciliSinif.ders}`:''}</Text></View><TouchableOpacity onPress={()=>setDetay(null)}><Text style={s.close}>✕</Text></TouchableOpacity></View><ScrollView contentContainerStyle={{paddingBottom:40}}><Text style={s.sectionTitle}>📊 Yoklama Geçmişi</Text>{studentAttendance(detay?.id).map(y=><View key={y.id} style={s.row}><Text>{y.tarihGosterim||y.tarih} {y.dersEtiketi?`• ${y.dersEtiketi}`:''}</Text><Text style={{color:y.durum==='geldi'?'#2E7D32':y.durum==='gecikti'?'#F57F17':'#C62828',fontWeight:'bold'}}>{y.durum==='geldi'?'Geldi':y.durum==='gecikti'?'Geç geldi':'Gelmedi'}</Text></View>)}<Text style={s.sectionTitle}>📚 Kitaplar ve Öğrenci Konuları</Text>{kitaplar.filter(k=>k.ogrenciId===detay?.id).map(k=>{const p=kitapIlerleme(k);return <View key={k.id} style={s.book}><Text style={s.cardText}>📖 {k.ad}</Text><Text style={s.small}>{p.done}/{p.total||'?'} sayfa • %{p.pct}</Text><View style={s.track}><View style={[s.fill,{width:`${p.pct}%`}]}/></View></View>})}{studentTopics(detay?.id).kitap.length?studentTopics(detay?.id).kitap.map(k=><View key={'kitap-'+k.id} style={s.rowBlock}><Text style={s.cardText}>{k.ad}</Text>{k.kitapAd?<Text style={s.small}>📖 {k.kitapAd}</Text>:null}{k.baslangicSayfa||k.bitisSayfa?<Text style={s.small}>Sayfa {k.baslangicSayfa}-{k.bitisSayfa}</Text>:null}</View>):null}<Text style={s.sectionTitle}>📘 Derste İşlenen Konular</Text>{studentTopics(detay?.id).ders.map(k=><View key={k.id} style={s.rowBlock}><Text style={s.cardText}>{k.ad}</Text>{k.tarih?<Text style={s.small}>{k.tarihGosterim||k.tarih}</Text>:null}{k.yoklamaDurumu==='gelmedi'?<Text style={s.absent}>❌ Derste yok</Text>:k.yoklamaDurumu==='gecikti'?<Text style={s.late}>⏰ Derste geç geldi</Text>:k.yoklamaDurumu==='geldi'?<Text style={s.present}>✅ Derste var</Text>:null}</View>)}<Text style={s.sectionTitle}>📋 Ödev Geçmişi — kronolojik</Text>{studentHomework(detay?.id).map(o=><View key={o.id} style={s.row}><View style={{flex:1}}><Text style={s.cardText}>{o.aciklama}</Text>{o.kitapAd?<Text style={s.small}>📖 {o.kitapAd}{o.baslangicSayfa||o.bitisSayfa?` • Sayfa ${o.baslangicSayfa}-${o.bitisSayfa}`:''}</Text>:null}<Text style={s.small}>Teslim: {o.teslimTarihi}</Text></View><Text>{statusText((o.ogrenciDurumlari||{})[detay?.id]||o.durum)}</Text></View>)}</ScrollView></View></Modal></View>}
const s=StyleSheet.create({wrap:{flex:1,backgroundColor:'#F1F8E9'},baslik:{fontSize:14,fontWeight:'bold',color:'#2E7D32',padding:14,paddingBottom:6},sinifListesi:{paddingHorizontal:12,maxHeight:75},sinifButon:{borderWidth:1,borderColor:'#C8E6C9',borderRadius:20,paddingHorizontal:14,paddingVertical:7,marginRight:8,backgroundColor:'#fff'},sinifAktif:{backgroundColor:'#2E7D32'},sinifMetni:{color:'#333',fontSize:13},sinifMetniAktif:{color:'#fff',fontWeight:'bold'},chipOkul:{fontSize:9,color:'#888',marginTop:2},chipOkulAktif:{fontSize:9,color:'#C8E6C9',marginTop:2},chipAlt:{fontSize:9,color:'#999',marginTop:2},chipAltAktif:{fontSize:9,color:'#C8E6C9',marginTop:2},sekmeler:{flexDirection:'row',backgroundColor:'#fff',padding:5},sekme:{flex:1,padding:9,alignItems:'center'},sekmeAktif:{backgroundColor:'#2E7D32',borderRadius:8},sekmeMetni:{fontSize:11,color:'#555'},sekmeMetniAktif:{fontSize:11,color:'#fff',fontWeight:'bold'},icerik:{padding:12},bos:{textAlign:'center',color:'#999',padding:30},card:{backgroundColor:'#fff',borderRadius:12,padding:13,marginBottom:8,elevation:1},cardText:{fontSize:14,color:'#333',fontWeight:'600'},student:{fontSize:15,fontWeight:'bold',color:'#1B5E20'},small:{fontSize:11,color:'#777',marginTop:3},detail:{flex:1,backgroundColor:'#F1F8E9',padding:14},detailHead:{backgroundColor:'#2E7D32',borderRadius:14,padding:14,flexDirection:'row',alignItems:'center'},detailTitle:{fontSize:19,fontWeight:'bold',color:'#fff'},close:{fontSize:25,color:'#fff',padding:8},sectionTitle:{fontSize:14,fontWeight:'bold',color:'#1B5E20',marginTop:16,marginBottom:7},row:{backgroundColor:'#fff',borderRadius:10,padding:11,marginBottom:6,flexDirection:'row',alignItems:'center',gap:8},rowBlock:{backgroundColor:'#fff',borderRadius:10,padding:11,marginBottom:6},book:{backgroundColor:'#fff',borderRadius:10,padding:11,marginBottom:7},track:{height:8,backgroundColor:'#E0E0E0',borderRadius:5,overflow:'hidden',marginTop:6},fill:{height:8,backgroundColor:'#2E7D32'},present:{color:'#2E7D32',fontSize:11,fontWeight:'bold',marginTop:5},late:{color:'#F57F17',fontSize:11,fontWeight:'bold',marginTop:5},absent:{color:'#C62828',fontSize:11,fontWeight:'bold',marginTop:5}});