import React,{useState,useEffect}from'react';
import {View,Text,TouchableOpacity,StyleSheet,ScrollView,Alert,ActivityIndicator,SafeAreaView}from'react-native';
import {collection,getDocs,query,where,addDoc,updateDoc}from'firebase/firestore';
import {auth,db}from'../firebaseConfig';
import {bugun,displayDate,oturumIdOlustur}from'../utils/oturum';
import {donemYiliBugun,donemUygun}from'../utils/donem';
const renk={geldi:'#2E7D32',gecikti:'#F57F17',gelmedi:'#C62828'},ikon={geldi:'✅',gecikti:'⏰',gelmedi:'❌'};
const GUNLER=['Pazar','Pazartesi','Salı','Çarşamba','Perşembe','Cuma','Cumartesi'];
const gunAdiTarih=t=>GUNLER[new Date(t+'T12:00:00').getDay()];
const ileriMi=t=>t>bugun();
const saatDakika=t=>{const[a,b]=String(t||'').split(':').map(Number);return(a||0)*60+(b||0)};
export default function YoklamaEkrani({route}){
 const routeDers=route?.params?.ders||null;const [siniflar,setSiniflar]=useState([]),[dersler,setDersler]=useState([]),[secili,setSecili]=useState(routeDers?{id:routeDers.sinifId,ad:routeDers.sinifAd,okulId:routeDers.okulId,okulAd:routeDers.okulAd,kademe:routeDers.kademe,ders:routeDers.ders}:null),[seciliDers,setSeciliDers]=useState(routeDers),[tarih,setTarih]=useState(route?.params?.oturumTarihi||bugun()),[ogr,setOgr]=useState([]),[durum,setDurum]=useState({}),[loading,setLoading]=useState(true),[saved,setSaved]=useState(false);
 const uid=auth.currentUser?.uid;const donemYili=Number(route?.params?.donemYili||routeDers?.donemYili||donemYiliBugun());const oturumId=seciliDers?oturumIdOlustur(seciliDers.id,tarih):null;
 useEffect(()=>{(async()=>{try{const[a,b]=await Promise.all([getDocs(query(collection(db,'siniflar'),where('uid','==',uid))),getDocs(query(collection(db,'dersler'),where('uid','==',uid)))]);const sl=a.docs.map(d=>({id:d.id,...d.data()})).filter(x=>donemUygun(x,donemYili));setSiniflar(sl);setDersler(b.docs.map(d=>({id:d.id,...d.data()})).filter(x=>donemUygun(x,donemYili)));if(routeDers){const s=sl.find(x=>x.id===routeDers.sinifId)||{id:routeDers.sinifId,ad:routeDers.sinifAd,okulId:routeDers.okulId,okulAd:routeDers.okulAd};setSecili(s);await yukleYoklama(routeDers,s,route?.params?.oturumTarihi||bugun())}else setLoading(false)}catch(e){Alert.alert('Hata','Sınıf ve dersler yüklenemedi.');setLoading(false)}})()},[]);
 const derslerBugun=()=>secili?dersler.filter(d=>d.sinifId===secili.id&&d.gun===gunAdiTarih(tarih)&&(!d.baslangicTarih||tarih>=d.baslangicTarih)&&(!d.bitisTarih||tarih<=d.bitisTarih)).sort((a,b)=>saatDakika(a.baslangicSaat)-saatDakika(b.baslangicSaat)):[];
 const yukleYoklama=async(d,s=secili,t=tarih)=>{if(!d||!s)return;setSeciliDers(d);setSecili(s);setLoading(true);try{const[os,ys]=await Promise.all([getDocs(query(collection(db,'ogrenciler'),where('sinifId','==',s.id),where('uid','==',uid))),getDocs(query(collection(db,'yoklamalar'),where('sinifId','==',s.id),where('uid','==',uid)))]);const list=os.docs.map(x=>({id:x.id,...x.data()})).filter(x=>donemUygun(x,donemYili));setOgr(list);const id=oturumIdOlustur(d.id,t),map={};list.forEach(o=>map[o.id]='geldi');ys.docs.map(x=>({id:x.id,...x.data()})).filter(x=>donemUygun(x,donemYili)).forEach(y=>{if(y.oturumId===id)map[y.ogrenciId]=y.durum});setDurum(map);setSaved(false)}catch(e){Alert.alert('Hata','Öğrenciler/yoklama yüklenemedi.')}setLoading(false)};
 const sinifSec=s=>{setSecili(s);setSeciliDers(null);setOgr([]);setDurum({});setSaved(false)};
 const tarihDegistir=delta=>{const d=new Date(tarih+'T12:00:00');d.setDate(d.getDate()+delta);const yeni=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;if(ileriMi(yeni))return;setTarih(yeni);setSeciliDers(null);setOgr([]);setDurum({});setSaved(false)};
 const kaydet=async()=>{if(!secili||!seciliDers)return Alert.alert('Hata','Önce sınıf ve ders seçin.');if(ileriMi(tarih))return Alert.alert('Hata','Gelecek güne ait yoklama alınamaz.');if(tarih===bugun()&&saatDakika(new Date().toTimeString().slice(0,5))<saatDakika(seciliDers.baslangicSaat))return Alert.alert('Hata',`Bu dersin yoklaması ${seciliDers.baslangicSaat} saatinden sonra alınabilir.`);setLoading(true);try{const id=oturumIdOlustur(seciliDers.id,tarih);for(const o of ogr){const q=query(collection(db,'yoklamalar'),where('ogrenciId','==',o.id),where('oturumId','==',id),where('uid','==',uid));const snap=await getDocs(q);const data={ogrenciId:o.id,ogrenciAd:o.adSoyad,sinifId:secili.id,sinifAd:secili.ad,okulId:secili.okulId||seciliDers.okulId||'',okulAd:secili.okulAd||seciliDers.okulAd||'',durum:durum[o.id]||'geldi',tarih,oturumId:id,dersId:seciliDers.id,dersEtiketi:`${seciliDers.baslangicSaat}–${seciliDers.bitisSaat} ${seciliDers.sinifAd}`,baslangicSaat:seciliDers.baslangicSaat||'',bitisSaat:seciliDers.bitisSaat||'',gun:seciliDers.gun||gunAdiTarih(tarih),uid,donemYili,olusturulma:new Date().toISOString(),tarihGosterim:displayDate(tarih)};if(snap.empty)await addDoc(collection(db,'yoklamalar'),data);else await updateDoc(snap.docs[0].ref,data)}setSaved(true);Alert.alert('Başarılı','Yoklama kaydedildi.')}catch(e){Alert.alert('Hata','Yoklama kaydedilemedi.')}setLoading(false)};
 const oz=Object.values(durum).reduce((a,x)=>{a[x]=(a[x]||0)+1;return a},{geldi:0,gecikti:0,gelmedi:0});
 if(loading&& !secili)return <ActivityIndicator style={{flex:1}} size="large" color="#2E7D32"/>;
 const gunDersleri=derslerBugun();
 return <SafeAreaView style={s.wrap}><View style={s.banner}><Text style={s.bannerT}>Yoklama</Text><Text style={s.bannerS}>{displayDate(tarih)} • {gunAdiTarih(tarih)}</Text></View><View style={s.dateNav}><TouchableOpacity style={s.dateBtn} onPress={()=>tarihDegistir(-1)}><Text>‹ Önceki Gün</Text></TouchableOpacity><View style={s.todayBox}><Text style={s.todayT}>{tarih===bugun()?'Bugün':displayDate(tarih)}</Text></View><TouchableOpacity style={[s.dateBtn,ileriMi(new Date(new Date(tarih+'T12:00:00').getTime()+86400000).toISOString().slice(0,10))&&s.disabled]} disabled={ileriMi(new Date(new Date(tarih+'T12:00:00').getTime()+86400000).toISOString().slice(0,10))} onPress={()=>tarihDegistir(1)}><Text>Sonraki Gün ›</Text></TouchableOpacity></View>{!secili&&<View style={s.panel}><Text style={s.label}>Sınıf seçin</Text><ScrollView>{siniflar.map(x=><TouchableOpacity key={x.id} style={s.row} onPress={()=>sinifSec(x)}><View style={{flex:1}}><Text style={s.name}>{x.ad}</Text><Text style={s.school}>{x.okulAd||'Okul belirtilmemiş'}</Text></View><Text>›</Text></TouchableOpacity>)}</ScrollView></View>}{secili&&!seciliDers&&<View style={s.panel}><Text style={s.label}>{secili.ad} — Ders seçin</Text>{gunDersleri.length?gunDersleri.map(d=><TouchableOpacity key={d.id} style={s.lesson} onPress={()=>yukleYoklama(d,secili,tarih)}><Text style={s.lessonTime}>{d.baslangicSaat}–{d.bitisSaat}</Text><Text style={s.lessonName}>{d.sinifAd}</Text><Text style={s.school}>{d.okulAd||secili.okulAd||''}</Text></TouchableOpacity>):<Text style={s.empty}>Bu gün için kayıtlı ders yok.</Text>}</View>}{secili&&seciliDers&&!loading&&<><View style={s.selected}><Text style={s.selectedClass}>{secili.ad} • {seciliDers.baslangicSaat}–{seciliDers.bitisSaat}</Text><Text style={s.selectedSchool}>{secili.okulAd||'Okul belirtilmemiş'} • {displayDate(tarih)}</Text></View><View style={s.summary}>{[['geldi','Geldi'],['gecikti','Geç geldi'],['gelmedi','Gelmedi']].map(([k,t])=><View key={k} style={s.sum}><Text style={s.num}>{oz[k]||0}</Text><Text>{ikon[k]} {t}</Text></View>)}</View><ScrollView contentContainerStyle={{padding:12,paddingBottom:150}}>{ogr.map((o,i)=>{const d=durum[o.id]||'geldi';return <TouchableOpacity key={o.id} style={[s.row,{borderLeftColor:renk[d]}]} onPress={()=>setDurum(p=>({...p,[o.id]:d==='geldi'?'gecikti':d==='gecikti'?'gelmedi':'geldi'}))}><View style={s.no}><Text>{i+1}</Text></View><Text style={s.name}>{o.adSoyad}</Text><Text style={[s.status,{backgroundColor:renk[d]}]}>{ikon[d]} {d==='geldi'?'Geldi':d==='gecikti'?'Geç geldi':'Gelmedi'}</Text></TouchableOpacity>})}</ScrollView><TouchableOpacity disabled={saved} style={[s.save,saved&&s.saved]} onPress={kaydet}><Text style={s.saveT}>{saved?'✅ Kaydedildi':'💾 Yoklamayı Kaydet'}</Text></TouchableOpacity></>}</SafeAreaView>}
const s=StyleSheet.create({wrap:{flex:1,backgroundColor:'#F1F8E9'},banner:{backgroundColor:'#2E7D32',padding:13},bannerT:{color:'#fff',fontWeight:'bold',fontSize:18},bannerS:{color:'#C8E6C9',marginTop:3},dateNav:{flexDirection:'row',alignItems:'center',padding:10,gap:6},dateBtn:{flex:1,backgroundColor:'#fff',borderWidth:1,borderColor:'#C8E6C9',padding:10,borderRadius:9,alignItems:'center'},todayBox:{paddingHorizontal:8},todayT:{fontWeight:'bold',color:'#1B5E20'},disabled:{opacity:.35},panel:{backgroundColor:'#fff',margin:12,borderRadius:14,padding:12,maxHeight:'55%'},label:{fontWeight:'bold',color:'#2E7D32',marginBottom:8},row:{backgroundColor:'#fff',borderLeftWidth:4,borderRadius:10,padding:12,marginBottom:7,flexDirection:'row',alignItems:'center'},name:{flex:1,fontWeight:'600',color:'#1B5E20'},school:{fontSize:11,color:'#777',marginTop:3},lesson:{backgroundColor:'#F9FBE7',borderWidth:1,borderColor:'#E8F5E9',borderRadius:10,padding:12,marginBottom:7},lessonTime:{fontWeight:'bold',color:'#2E7D32',fontSize:16},lessonName:{fontWeight:'bold',marginTop:3},empty:{padding:20,textAlign:'center',color:'#999'},selected:{margin:12,backgroundColor:'#E8F5E9',borderRadius:10,padding:11},selectedClass:{fontWeight:'bold',color:'#1B5E20'},selectedSchool:{fontSize:11,color:'#558B2F',marginTop:3},summary:{flexDirection:'row',gap:7,padding:10},sum:{flex:1,backgroundColor:'#fff',borderRadius:10,padding:9,alignItems:'center'},num:{fontSize:20,fontWeight:'bold',color:'#1B5E20'},no:{width:28,height:28,borderRadius:14,backgroundColor:'#E8F5E9',alignItems:'center',justifyContent:'center',marginRight:10},status:{color:'#fff',fontWeight:'bold',borderRadius:12,paddingHorizontal:9,paddingVertical:5},save:{position:'absolute',left:12,right:12,bottom:78,backgroundColor:'#2E7D32',padding:16,borderRadius:12,alignItems:'center'},saved:{backgroundColor:'#81C784'},saveT:{color:'#fff',fontWeight:'bold'}});